### ISSUE TITLE
Autoresizing often fails

### ISSUE THREAD

**Issue by AgentRev** [Owyn/HandyImage#415] opened 2021-04-11 07:43 UTC
On some websites like ImageFap, autoresizing often completely fails to work.

I have observed 2 different causes for this:

1. Sometimes, when `onVisibilityChange()` is called by `makeimage()`, `document.visibilityState` somehow stays stuck on `'hidden'`, preventing `autoresize();` from ever being reached. This may or may not be related to `removeAllListeners()` being called prematurely. Commenting out `removeAllListeners();` seems to greatly reduce the likelyhood of getting stuck on `'hidden'`, but might not be the root cause.

2. Sometimes,`i.naturalWidth` evaluates to `0` inside of `autoresize()`, causing a fallback onto the ARC `setTimeout` kludge. However, it seems that `document.write('<html><head></head><body></body></html>');` disables all timeouts, thus stalling the ARC kludge before `i.naturalWidth` goes above `0`.

Script version: 2021.04.07
Chrome version: 89.0.4389.114

**Comment by Owyn** [comment] 2021-04-11 16:41
Line 906:
```
document.addEventListener("visibilitychange", onVisibilityChange);

unsafeWindow.addEventListener = protected_addEventListener;
```
so `onVisibilityChange` can't being removed by `removeAllListeners()` since it removes only listeners added after `visibilityChange`

> document.write('<html><head></head><body></body></html>'); disables all timeouts

yes but again, it's called before it even starts listening for `visibilityChange` event ?.?

```
document.write('<html><head></head><body></body></html>');
				document.close();
				document.addEventListener("visibilitychange", onVisibilityChange);
				```
				
				checked `ARC` variable and it's still `0` here, so it hasn't run yet to make any timeouts
				
				tested Chrome an it seems now document.write is very lazy (async) so adding listener right after writing it kinda fails silently
				
				fixed in latest version, thx for reporting (cuz I use Firefox so I don't notice any Chrome problems)

**Closed by Owyn** 2021-04-11 16:41 UTC

**Comment by AgentRev** [comment] 2021-05-31 19:55
@Owyn So, a bit of feedback; the fix you made has only ever work partially. If you open the link to a new tab, let the tab fully load, then switch to that tab, resizing works. However, if you click on the picture to load the link in the current tab, it doesn't resize properly. Additionally, if Chrome session settings are set on "Continue where you left off", and you restart Chrome while having picture links open, none of the pictures from restored tabs will resize properly if you click on a tab without first refreshing it via right-click and letting it fully load.

**Comment by Owyn** [comment] 2021-06-01 15:05
> if you click to open a link in the current tab, it doesn't resize properly.

I can't reproduce it in Chrome 88 anyhow, works fine here

lemme update to latest chrome 91... yeap it's broken now


fixed it again.
